blank_issues_enabled: false
contact_links:
  - name: Help/Support
    url: https://obsproject.com/forum/threads/xobsbeam-beta.165709/
    about: Questions or issues about how to use and configure Beam
